services:
  nwafu-connect:
    build:
      context: .
    image: nwafu-connect
    container_name: nwafu-connect
    restart: unless-stopped
    ports:
      - 1080:1080
      - 1081:1081
    volumes:
      - ./config.toml:/home/nonroot/config.toml